---
kind: pipeline
type: kubernetes
name: node13

steps:
  - name: test node 13
    image: node:13
    commands:
      - npm i
      - npm run test
services:
  - name: mongo
    image: mongo:latest

---
kind: pipeline
type: kubernetes
name: node14

steps:
  - name: test node 14
    image: node:14
    commands:
      - npm i
      - npm run test
services:
  - name: mongo
    image: mongo:latest

---
kind: pipeline
type: kubernetes
name: node15

steps:
  - name: test node 15
    image: node:15
    failure: ignore
    commands:
      - npm i
      - npm run test
services:
  - name: mongo
    image: mongo:latest
