language: node_js
node_js:
- 10
- 12
- 13
matrix:
  allow_failures:
  - node_js: 13
os:
- linux
- macosx
cache:
  directories:
  - node_modules
services:
- mongodb
install:
- npm i
before_script:
- npm rebuild bcrypt --update-binary
- npm run test:coveralls
jobs:
  include:
  - stage: deploy
    if: branch = master
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - scripts/deploy-travis.sh
