version: '3'

services:

  waosnode:
    container_name: waosnode
    image: waosnode:latest
    restart: always
    ports:
      - 3000:3000
    volumes:
      - waosnode:/data
    networks:
      - mongo
    depends_on:
      - mongo
    environment:
      - "WAOS_NODE_db_uri=mongodb://mongo:27017/WaosNodeDev"
      - "WAOS_NODE_host=0.0.0.0"

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongo:/data
    networks:
      - mongo
      
networks:
    mongo:
      driver: bridge

volumes:
  waosnode:
  mongo: